#!/usr/bin/env python

# calculate percentage after time amount test
import sys
if sys.argv[1] == "-h":
	print("arg1[Interval], arg2[initial amount], arg3[interest/percent gain]")
elif len(sys.argv) < 2:
	print("Missing arg 1")
elif len(sys.argv) < 3:
	print("Missing arg 2")
elif len(sys.argv) < 4:
	print("Missing arg 3")
else:
	interval = int(sys.argv[1])
	ini_amount = float(sys.argv[2])
	perc_gain = float(sys.argv[3]) * .01
	calc_amount = ini_amount

	for x in range(interval):
		calc_amount = calc_amount + (calc_amount * perc_gain)
	
    #round calcumated amount for presentation
	calc_amount = round(calc_amount,2)
	
	print("initial amount: $" + str(ini_amount))
	print("Interval: " + str(interval))
	print("Percentage gain over interval: " + str(round(perc_gain * 100)) + "%")
	print("")
	print("final amount: $" + str(calc_amount))